### ISSUE TITLE
Migrate UI to Proper MVVM Framework

### ISSUE THREAD

**Issue by joadoumie** [zadjii-msft/PowerToys#73]
### Description of the new feature / enhancement

Currently the UI/UX lives in a prototype project (Microsoft.CmdPal.UI.POC) and when the project is built, this UI is what is being leveraged. 

We need to finalize the migration to a proper MVVM model -- the Microsoft.CmdPal.UI & Microsoft.CmdPal.UI.ViewModels

### Scenario when this would be used?

This will become the underlying infrastructure of the project.

**Comment by zadjii-msft** [comment]
Leaving notes here. Just thoughts I was having for the post-#153 changes. I'll probably edit with updates as I go

------------------------




* `CommandItemViewModel : ObservableObject`: A base class for `ICommandItem`. 
  * `string Title`, `string Subtitle`, `IconDataType Icon`, `string Name`: Pretty much all self-explanatory
  * `ExtensionObject<ICommandItem> Command`: The raw object returned by `TopLevelItems`, if the item _isn't_ a stub
    * 📝: this should probably be wrapped in something that makes it clear - accessing this object is potentially cross-proc

---------------------------------

* `TopLevelCommandModel : CommandItemViewModel`: A wrapper for a top-level command. This may or may not have a live object backing it.
  * `bool IsStub`: is this object a recreation of a top-level command, or backed by a real live one?
  * 📝: The `Command` in the base `CommandItemViewModel` may or may not be a live object. If this is a stub, that object is `null`. 
  * `TODO_SomeProviderWrapperReference Provider`: the extension the command came from


When we call `TopLevelItems`, we'll get back a list of `ICommandItem`s We stick those into `TopLevelCommandModel`'s to wrap them up. We'll pull out all the `ICommandItem` properties, async, and put into the base `CommandItemViewModel` members (to cache them). 

---------------------------------

* `ListItemViewModel : CommandItemViewModel`: The Viewmodel for a list item
  * `static ListItemViewModel FromCommandItem(CommandItemViewModel)`
  * `static ListItemViewModel FromListItem(ExtensionObject<IListItem>)`



Every list page is comprised of a list of `ListItemViewModel`s. 
Those `LIVM`s are either backed by:
* some chain of objects leading to a `IListItem`  (for items on list pages, returned from live extensions)
  * `ListItemViewModel` -> `ExtensionObject<IListItem>` -> `IListItem`
* some chain of objects leading to a `ICommandItem` (for top level items) 
  * `ListItemViewModel` -> `CommandItemViewModel` -> `IListItem`

---------------------------------

I feel like I've added too many layers of inheritance. This doesn't feel right.

**Comment by michael-hawker** [comment]
I'm trying to think if we need a distinction between the commands and the list items, or if everything is just a list item which may or may not be/have a command?

I also feel like we can use the ViewModel for an item to abstract away the loading aspect of it (i.e. if its 'live' or not), as we still need something to display if it's a stub. It just means when interacting with those stubs, that that there may be more of a delay that we have to account for in the UI layer.

That's how I'd try and look at it though and then only abstract/break-apart further if we see a good reason to have those level of separation?

This is where the two of us just need to merge upon our understandings of both sides. 😅

**Comment by zadjii-msft** [comment]
Yea a lot of my thoughts here are based on the changes I'm typing up based on https://github.com/zadjii-msft/PowerToys/issues/153#issuecomment-2486367825, which is then also based on the ideas in #160. That's what I get for not finishing all the spec bits faster 😅 But I think in that world, things are more sane, because both "stub" and live top-level `ICommandItem`s are really just the same collection of properties. It's just the seamless translation between `{TopLevel}CommandItemModel` and the `ListItemViewModel` that I need to wrap my head around

I'll go type that as fast as I can, and then hopefully we get aligned on this and not have to worry about it again

**Comment by zadjii-msft** [comment]
Some notes from being up in the night with Luca. ~Not sure how sane they are yet.~

---------------

Okay so what we're going to do is we're going to make the `ListPage` take a collection of `IListItemViewModel`s. `I`. Then `TopLevelCommandViewModel` is an `IListItemViewModel` and a `ListItemViewModel` is an `IListItemViewModel` so they share the same interface. We use that interface as what we're rendering.
That way, the top level commands can be backed by a different model then the list items and we don't have to make a `ListItem` just to hold the top level command item.

------

Could we have like an `async Task InitializeProperties()` method on the base `ExtensionObjectViewModel` that does the initial fetch? Then after that, we just use `PropChanged` for everything 

Alternative might be a core `ExtensionObject` model, where each property on that object is an async read. Then the viewmodel does the async reading of those things. But, eh, that sounds more annoying. 

-------

So, then we've got:


* `ExtensionObjectViewModel : ObservableObject { abstract async Task InitializeProperties(); }`
* `CommandItemViewModel : ExtensionObjectViewModel`
* `ListItemViewModel : CommandItemViewModel, IListItemViewModel`
* `TopLevelCommandViewModel : CommandItemViewModel, IListItemViewModel`
  * Is a `TopLevelCommandViewModel` just a `ListItemViewModel`? 
    * no. The TLC might be a stub, and is ultimately not backed on a `IListItem` 
  * We may want this to _not_ extend from `CommandItemViewModel`, based solely on the fact that it may be backed by a stub and not an actual `ICommandItem`. But we do want `IListItemViewModel`, so that we can use it in the list
* `ContextCommandViewModel : CommandItemViewModel`


-------


Okay I've re-read this, and it makes sense to me.

**Comment by zadjii-msft** [comment]
other thoughts but baby woke up. will edit when I'm back from lunch

What we still need:

* Some sort of Core project for models
* In the Core project, there's gotta be an `IExtensionService` 
  * Looks like I had something like that in the Prototype, used in `MainPage.Xaml.cs:LoadExtensions()`
  * The extension service needs to be able to be told to load our extension objects
    * As it fetches a command provider from an extension, it needs to notify.... 
      * ~the `ShellViewModel`(? maybe just model? )~
      * Probably needs to notify some sort of `CommandProviderManager` service that owns all the command providers we've loaded
    * {{that owner}} needs to then fetch the `TopLevelCommands` from the `CommandProvider`
      * it'll wrap them in `TopLevelCommandViewModels`, 
      * and off the UI thread, it'll call `InitializeProperties()`
      * Once that's done, it'll ↴
    * {{that owner}} then needs to tell (the `ShellViewModel`?) that the are more `TopLevelCommands`
      * which then get added to the `MainListPage` (which is a `ListPage` extension object)
        * which will then take those and stick them in `Collection<IListItemViewModel> MainListPage._items`
        * then it'll 


We probably need to have `IListPageViewModel`, and have both `ListPageViewModel` and `MainListPageVM` implement that seperately. Cause a ListPageVM needs to retrieve items from an extension, while the main page _doesn't_

**Comment by zadjii-msft** [comment]
```mermaid
flowchart TD

    subgraph Out-of-proc Models
        IListItem[IListItem]
        ICommandItem[ICommandItem]
        ICommand[ICommand]
        IListPage[IListPage]
        ICommandProvider[ICommandProvider]
    end

    subgraph In-proc Models
    
        ExtensionManager([ExtensionManager])
        TopLevelCommandWrapper([TopLevelCommandWrapper])

        ICommandItem -. Might be referenced by ..-> TopLevelCommandWrapper
        ExtensionManager -- produces --> TopLevelCommandWrapper
        
        TopLevelCache[(TopLevelCache)]
        TopLevelCache -- produces --> TopLevelCommandWrapper
        
        MainPage([MainPage])
        TopLevelCommandWrapper -- contained in --> MainPage

    end

    ICommandProvider ---> ExtensionManager

    subgraph ViewModels
        ListPageVM([ListPageVM])
        ShellPageVM([ShellPageVM])
        FilterBoxVM([FilterBoxVM])
        CommandBarVM([CommandBarVM])
        ListItemVM([ListItemVM])
    end

    ICommand --> ICommandItem
    ICommandItem x-. extends .-x IListItem

    TopLevelCommandWrapper x-. implements .-x IListItem
    IListItem ---> ListItemVM
    ListItemVM -- rendered by ---> ListPageVM

    IListItem -- contained in --> IListPage
    IListPage --> ListPageVM
    MainPage x-. implements .-x IListPage


    ShellPageVM -- navigates to --> ListPageVM
    ShellPageVM -- owns --> CommandBarVM
    ShellPageVM -- owns --> FilterBoxVM

```

```cs
class MainPage : IDynamicPage {
    Collection<TopLevelCommandWrapper> _topLevelCommands = new();
    IListItem[] GetItems() => _topLevelCommands.ToArray();
}

class TopLevelCommandWrapper : IListItem {
    public static TopLevelCommandWrapper FromStub();
    public static TopLevelCommandWrapper FromExtension(ICommandItem item);
}

class ListItemViewModel
{
    ExtensionObject<IListItem> _model;
    async Task InitializeProperties(); 
}
class ListPageViewModel
{
    ExtensionObject<IListPage> _model;
    async Task InitializeProperties(); 
    async Task FetchItems();
}
```

This way, `ListPageVM` and `ListItemVM` only ever need to think about `IListPage`s and `IListItem`s. The VM's will always be smart enough to access properties from these models off the UI thread, even if the models secretly are in-proc.

`TopLevelCommandWrapper` owns all the logic for knowing if it was backed by a live `ICommandItem` or not.  (We'll just start with all live objects)

The `MainPage` is our in-proc model for the top-level list. It's a `IDynamicListPage`. We'll initialize it with something like an `TopLevelCommandManager`. That `TLCManager` will start by returning all the builtins, then also kick off loading TLCs from cache and extensions. 

As we load top level commands, we'll drop them into `MainPage`, who'll raise `ItemsChanged` to let the `ListPageVM` know to fetch the new items.

**Comment by zadjii-msft** [comment]
```mermaid

classDiagram
    namespace Shell{
        class ShellPage{
            -ShellVM ViewModel
            -FilterBox Filter
            -CommandBar CommandBar
        }
        class ShellVM{
        }
    }
    namespace Filter {
        class FilterBox{
            -FilterBoxVM ViewModel
            TextChanged(string)
        }
        class FilterBoxVM{
            +TextChanged(string)
        }

    }
    namespace CommandB {

        class CommandBar{
            -CommandBarVM ViewModel
        }
        class CommandBarVM{
            +ContextItemVM[] ContextMenuCommands
            +bool HasContextMenu
            UpdateSelectedItem(CommandItemVM)
        }
    }

    namespace ContextMenu{
        %% class ContextListItem{
        %% }

        class ContextItemVM{
            +ContextItemVM[] ContextMenuCommands
            +bool HasContextMenu
        }

    }

    namespace LP{
        class ListPage{
            -ListVM ViewModel
        }

        class ListVM{
            +bool HasDetails
            +bool ShowDetails
            +string PlaceholderText
            +string SearchText
            +UpdateSelectedItem()
            +FilterTextChanged(string)
        }
    }

    class CommandItemVM {
        +string Title
        +string Subtitle
        +IconViewModel Icon
    }

    namespace LI{

        %% class ListItem{
        %% }
        class ListItemVM{
            +TagViewModel[] Tags
            +string SuggestedText

            +Invoke()
            +AcceptSuggestion()
        }
    }

    %% ContextItemVM --|> CommandItemVM : inherits from
    %% ListItemVM --|> CommandItemVM : inherits from
    CommandItemVM --|> ListItemVM
    CommandItemVM --|> ContextItemVM

    ShellPage --* ShellVM
    ShellPage --* FilterBox
    ShellPage --* CommandBar

    ListPage --* ListVM
    FilterBox --* FilterBoxVM
    CommandBar --* CommandBarVM

    CommandBarVM --o "0..*" ContextItemVM
    ListVM --o "0..*" ListItemVM

    %% =================== MESSAGES ===================
    %% ViewModels --> Views
    ListVM --> FilterBox : SearchTextChanged
    ListVM --> FilterBox : PlaceholderTextChanged
    
    %%% TODO: Should this go to the CommandBarVM, 
    %%% as a Command? rather than a message?
    ContextItemVM --> CommandBar : ShowSubmenu

    %% ListVM --> ShellPage : PerformCommand
    %% ContextItemVM --> ShellPage : PerformCommand
    %% ListItemVM --> ShellPage : PerformCommand
    ListVM --() PerformCommand 
    ContextItemVM --() PerformCommand 
    ListItemVM --() PerformCommand 
    PerformCommand ()-- ShellPage 
    
    ListVM --> CommandBar : UpdateSelectedItem
    ListItemVM --> FilterBox : UpdateSuggestion
    FilterBoxVM --> ListPage : FilterTextChanged
    FilterBoxVM --> ShellPage : GoBack



```

**Comment by zadjii-msft** [comment]
Some notes from the weekend. These are mostly based off work in `dev/migrie/f/bind-page-info`, branched from #176 

Page loading probably needs another big update on top of what we've already got

* Most pages kinda have a two-step load. 
  * First we need to get out basic properties like the page name, icon, search placeholder text, is it loading - stuff like that. 
  * Then we need to retrieve the _content_
    * For lists: this is `GetItems`
    * For markdown: `Bodies()`
    * For forms: `Forms()`
    * ASIDE: weird that those don't also have `Get` in their names.
* We want to navigate to the page immediately when the user activates that action,
  * at this point, the shell should update itself into a basic page loading state. Clear out the old page name/color/icon/command bar/filter, and start the loading bar. 
* BG: Then start fetching the basic properties. Each one of these calls is a x-proc call.[^3]
  * FG: Use those to populate the command bar and filter bar as needed.
* BG: Then kick off the call to fetch the content
  * When content comes in, stick it on the UI on the UI thread
* At any point, the page may hit an exception loading data from the extension. Anywhere. 
  * I think we need a `IRecipient` handler for "Show an exception in this page". Cause that can be raised almost anywhere - in the `ListViewModel`, on the `ListItemViewModel`, the `CommandContextItemViewModel`, anywhere we're operating on `ExtensionObject<>`s
  * We also need to be extra clever about this in the main page. But at least that's got the `MainPage` model, which we should be able to use to wrap up any calls to top-level commamnds and eat exceptions from them when we're displaying them in the L0

---

Other notes on "observable" extension objects:
* `INotifyPropChanged` is our interface for extension objects that want to notify us that their properties changes. 
* When we're handling `INotifyPropChanged` in the host app, that's _always_ on a BG thread. 
  * As currently designed, `INotifyPropChanged` doesn't include the _value_ of the property that changed - only the name. So when we get that notification, we need to make another (unsafe) hop x-proc to retrieve the property's value
    * I wonder if we can't include a PropertySet or something similar in the event payload to carry the new value to the host.[^1] IIRC `PropertySet` or something like it can be passed by-value across the ABI, rather than as a reference[^2]
  * **Once we have the value**, we need to raise a real `PropertyChanged` on the UI thread (correct? we can't change VM properties on a BG thread?)
    * This is definitely awkward to do currently. That resulted in clode that looked like:

```cs
    private void Model_PropChanged(object sender, PropChangedEventArgs args) {
        try {
            var propName = args.PropertyName;
            FetchProperty(propName);
        }
        catch (Exception) { /* TODO log? throw? */ }
    }
    protected virtual void FetchProperty(string propertyName)
    {
        var model = this._pageModel.Unsafe;
        if (model == null) { return;  /* TODO log? throw? */ }
        // We're not really safe here, but at least we're already in the try/catch in Model_PropChanged
        switch (propertyName)
        {
            case nameof(Name):
                // Get the new value (RPC)...
                var newName = model.Name ?? string.Empty;
                // ... then update UI 
                Task.Factory.StartNew(() => { this.Name = newName; }, CancellationToken.None, TaskCreationOptions.None, Scheduler);
                break;
            case nameof(Loading):
                var newLoading = model.Loading;
                Task.Factory.StartNew(() => { this.Loading = newLoading; }, CancellationToken.None, TaskCreationOptions.None, Scheduler);
                break;
            // Etc for more properties
        }
    }
```
* there's another weird thing I was hitting with event handlers that might disappear, #181, which I need to follow up with the CsWinRT folks about

[^1]: I had half a thought falling asleep: what if we could serialize a whole object to a property set, and then just get that in like, a `GetProperties` call at the start? What if we could include nested property sets? a propertyset is basically json right? could we use that for the JS extensions somehow?
[^2]: After some research, this may be `MarshalByValueValueSet`, which I _don't_ think is available publicly. 
[^3]: We're not using structs for these objects, because winrt structs can't change their size across ABI versions. We can't have a `struct Command` and then later intorduce a `struct Command2` that adds additional properties.

**Comment by michael-hawker** [comment]
Ah, was going to open a new issue, but saw this was re-opened, and seems like a good spot to keep these architecture discussions.

Looking at filtering, I realized the SearchBar currently doesn't have a notion of what page we're on yet, and thus no reference to the ViewModel to tell the page to filter...

This is also something the ActionBar needed as plumbed in to it's VM here: https://github.com/zadjii-msft/PowerToys/pull/186.

We also have it exposed as itself view ListViewModel and the ViewModel property in its view of ListPage.xaml.

To that end I think we need to come up with a common notion of what the CurrentPage is and how that works. And possibly create a BasePageView all our different view pages can inherit from so they understand that context, and a way that our various UI components understand what the current page is (currently searchbar / actions).

We could do some stuff with messaging here, but it feels like this is central enough of a concept, that we should just ensure everything understands what the CurrentPage is in the app and manage that under the hood, then that way if we add a new UI component to the experience or a new type of page, it'll be easier for folks to just build quickly with what they need than having to manage this themselves.

Does this make sense?

----

I think we have enough in the current prototype to understand the scope of the problem. I think the question is where it makes the most sense to manage this from.

It's probably the `ShellViewModel` which is pretty sparse at the moment, and since it will also own the "Main Page", it seems like a good place to manage the understanding of what's "current"

We also already in its view pass the PageViewModel to the navigated page, so if we create a base class for the views, this seems like a simple thing to auto-populate in centralized navigation code.

We then have two options:
1) Expand/continue to use the `UpdateActionBarPageMessage` (looks like we accidentally duped this) message to just be a `CurrentPageChangedMessage` for whatever needs to listen to this.
2) Bind and pass the new `ShellViewModel.CurrentPage` reference to the dependent controls of SearchBox and ActionBar, then all bindings should flow when that changes in the shell. We'd just want to ensure we have proper handling for loading states (as we want to do already).

We're currently more setup for 1, but 2 is the more canonical approach and hopefully would result in less code as it'd all be managed by XAML.

The only downside to 2 is if we have other things outside our main shell that need to know about it, but we could add back on other routing/services or a message if that time comes in the future.

Any concerns if I just go jam on trying out approach 2? Any questions?

**Comment by zadjii-msft** [comment]
(we talked in chat and we're going with option 2)

**Comment by zadjii-msft** [comment]
oh dear i might have too many branches in progress at the moment

```mermaid
gitGraph
    commit id: "Niels9001/ux explorations (#174)"
    commit id: "ListViewModel Loading Pattern (#180)"
    commit id: "Load extensions into TRA (#176)"
    commit id: "merge PT main 4"
    commit id: "Bind to Page #186"
    branch dev/migrie/tag-vm
    commit id:"more viewmodels"
    commit id:"render them"
    commit id:"43c5642f0"
    branch dev/migrie/details-vm-prebase
    checkout dev/migrie/details-vm-prebase
    commit id: "5ff225216 Add a basic DetailsViewModel"
    checkout main
    commit id: "Add the All Apps page to the MVVM app. (#190)"
    commit id: "Adding extensions SDK nuget generation (#184)"
    commit id: "Add the shell plugin from PT Run, and a ChoiceSet settings helper (#185)"
    commit id: "Merge pull request #198 from zadjii-msft/user/ejohn/sdkFix"
    branch dev/migrie/b/fix-build-webview2
    checkout dev/migrie/b/fix-build-webview2
    commit
    commit id:"e847ece9e"
    checkout dev/migrie/tag-vm
    branch dev/migrie/f/colors-in-sdk
    checkout dev/migrie/f/colors-in-sdk
    commit id:"Add M.T.Core.Color to this project"
    commit
    commit
    commit id:"8bde437df Loading should be IsLoading"
    
    branch dev/migrie/f/icon-factory
    checkout dev/migrie/f/icon-factory
    commit
    commit
    commit id:"d3dace386 I think that's all the icons again"
    checkout dev/migrie/f/colors-in-sdk
    commit id:"04ec60504 I agree, HasMoreItems is better"

    checkout dev/migrie/b/fix-build-webview2
    branch dev/migrie/f/fallback-shell-command
    checkout dev/migrie/f/fallback-shell-command
    commit id:"ac9b44a16 Add a fallback command for she shell command extension"
    commit id:"4f5826b28"

    checkout dev/migrie/details-vm-prebase
    branch dev/migrie/f/details-view-prebase
    checkout dev/migrie/f/details-view-prebase
    commit
    commit
    commit id: "6bbbe2508 some better styling"
    
    checkout dev/migrie/b/fix-build-webview2
    branch dev/migrie/f/obsidian-extension
    checkout dev/migrie/f/obsidian-extension
	commit
```
